application: scorecardbuilder-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static/js
  static_dir: scripts

- url: /static/css
  static_dir: stylesheets

- url: /.*
  script: driver.app

libraries:
- name: jinja2
  version: latest
