application: scorecardbuilder
version: 1
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /static/js
  static_dir: scripts

- url: /static/css
  static_dir: stylesheets

- url: /.*
  script: driver.py

